services:
  - type: web
    name: iwwamo-web
    env: docker
    plan: free
    repo: https://github.com/CrepinAradjo228/PPE-301-ARADJO-CREPIN-ET-AYANA-THAWFIK.git
    branch: master
    buildCommand: "docker build -t iwwamo-web ."
    region: frankfurt
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: iwwamo-db
          property: connectionString

databases:
  - name: iwwamo-db
    databaseName: iwwamo_app
    user: iwwamo_user
    plan: free
