# Generated by Django 5.1.6 on 2025-05-10 11:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('sexe', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=18)),
                ('numero', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('password1', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('client', 'Client'), ('proprietaire', 'Proprietaire')], default='client', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('localisation', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('etat', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='biens/')),
            ],
        ),
        migrations.CreateModel(
            name='TypeBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IMMOBILIER_APP.utilisateur')),
            ],
            bases=('IMMOBILIER_APP.utilisateur',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IMMOBILIER_APP.utilisateur')),
            ],
            bases=('IMMOBILIER_APP.utilisateur',),
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IMMOBILIER_APP.utilisateur')),
            ],
            bases=('IMMOBILIER_APP.utilisateur',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titrefoncier', models.ImageField(upload_to='Piècesbiens/')),
                ('carterecto', models.ImageField(null=True, upload_to='Piècesbiens/')),
                ('carteverso', models.ImageField(null=True, upload_to='Piècesbiens/')),
                ('planbien', models.ImageField(null=True, upload_to='Piècesbiens/')),
                ('nature_publication', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('datepublication', models.DateField(default=datetime.date.today)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='IMMOBILIER_APP.bien')),
            ],
        ),
        migrations.AddField(
            model_name='bien',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMMOBILIER_APP.typebien'),
        ),
        migrations.CreateModel(
            name='Louer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_location', models.DateField()),
                ('duree_location', models.IntegerField(default=0)),
                ('Bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMMOBILIER_APP.bien')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMMOBILIER_APP.client')),
            ],
        ),
        migrations.CreateModel(
            name='Acheter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateField()),
                ('Bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMMOBILIER_APP.bien')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMMOBILIER_APP.client')),
            ],
        ),
    ]
