# Generated by Django 5.1.6 on 2025-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
