# Generated by Django 5.1.6 on 2025-05-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0002_alter_utilisateur_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('proprietaire', 'Proprietaire')], default='proprietaire', max_length=20),
        ),
    ]
