# Generated by Django 5.1.6 on 2025-05-26 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0005_vendre_numero_titre_foncier_vendre_titre_foncier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='louer',
            name='proprietaire',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, to='IMMOBILIER_APP.utilisateur'),
        ),
        migrations.AlterField(
            model_name='vendre',
            name='proprietaire',
            field=models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, to='IMMOBILIER_APP.utilisateur'),
        ),
    ]
