# Generated by Django 5.1.6 on 2025-06-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0006_alter_louer_proprietaire_alter_vendre_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendre',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
