# Generated by Django 5.1.6 on 2025-06-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0008_bien_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='louer',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('disponible', 'Disponible'), ('loue', 'Loué'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
