# Generated by Django 5.1.6 on 2025-07-02 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0009_louer_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('vente', 'Demande pour une vente'), ('location', 'Demande pour une location')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('est_traitee', models.BooleanField(default=False)),
                ('bien_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_location', to='IMMOBILIER_APP.louer')),
                ('bien_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_vente', to='IMMOBILIER_APP.vendre')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_client', to='IMMOBILIER_APP.utilisateur')),
            ],
        ),
    ]
