# Generated by Django 5.1.6 on 2025-07-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0010_demandebien'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandebien',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='demandebien',
            name='nom_complet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demandebien',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
