# Generated by Django 5.1.6 on 2025-07-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0011_demandebien_email_demandebien_nom_complet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandebien',
            name='demandeur',
        ),
    ]
