# Generated by Django 5.1.6 on 2025-07-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0012_remove_demandebien_demandeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='louer',
            name='statut',
            field=models.CharField(choices=[('enregistre', 'Enregistré (En attente de publication)'), ('en_attente', "En attente de validation (pour l'administrateur)"), ('publie', 'Publié'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendre',
            name='statut',
            field=models.CharField(choices=[('enregistre', 'Enregistré (En attente de publication)'), ('en_attente', "En attente de validation (pour l'administrateur)"), ('publie', 'Publié'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
