# Generated by Django 5.1.6 on 2025-07-03 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0013_alter_louer_statut_alter_vendre_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(default=0, limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, to='IMMOBILIER_APP.utilisateur'),
            preserve_default=False,
        ),
    ]
