# Generated by Django 5.1.6 on 2025-07-03 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0014_bien_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMMOBILIER_APP.utilisateur'),
        ),
    ]
