# Generated by Django 5.1.6 on 2025-07-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0015_alter_bien_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='statut',
            field=models.CharField(choices=[('enregistre', 'Enregistré'), ('publie', 'Publié'), ('disponible', 'Disponible')], default='enregistre', max_length=10),
        ),
    ]
