# Generated by Django 5.1.6 on 2025-07-22 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0016_alter_bien_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandebien',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandebien',
            name='date_demande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=100, verbose_name='Nom du Client')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email du Client')),
                ('client_telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du Client')),
                ('type_transaction', models.CharField(choices=[('vendu', 'Vendu'), ('loue', 'Loué'), ('annule', 'Annulé')], max_length=10, verbose_name='Type de Transaction')),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la Transaction')),
                ('montant_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Montant de la Transaction')),
                ('statut_bien_apres_transaction', models.CharField(choices=[('vendu', 'Vendu'), ('loue', 'Loué'), ('annule', 'Annulé')], max_length=10, verbose_name='Statut du Bien Après Transaction')),
                ('bien_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_location', to='IMMOBILIER_APP.louer', verbose_name='Bien Loué')),
                ('bien_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_vente', to='IMMOBILIER_APP.vendre', verbose_name='Bien Vendu')),
                ('demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_liee', to='IMMOBILIER_APP.demandebien', verbose_name='Demande Associée')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_proprietaire', to='IMMOBILIER_APP.utilisateur', verbose_name='Propriétaire du Bien')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
