# Generated by Django 5.1.6 on 2025-08-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0017_demandebien_date_traitement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendre',
            name='cloturer',
            field=models.BooleanField(default=False, help_text='Indique si la vente est clôturée ou non'),
        ),
    ]
