# Generated by Django 5.1.6 on 2025-08-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0018_vendre_cloturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandebien',
            name='duree_location_mois',
            field=models.PositiveIntegerField(blank=True, help_text='Durée minimale souhaitée par le client (en mois)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_fin_location',
            field=models.DateField(blank=True, null=True),
        ),
    ]
