# Generated by Django 5.1.6 on 2025-08-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0019_demandebien_duree_location_mois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_debut_location',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Début de Location'),
        ),
    ]
