# Generated by Django 5.1.6 on 2025-08-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0020_transaction_date_debut_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RenouvelerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('duree_nouvelle_location', models.PositiveIntegerField(help_text='Durée en mois')),
                ('date_renouvellement_demande', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMMOBILIER_APP.louer')),
            ],
        ),
    ]
