# Generated by Django 5.1.6 on 2025-08-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0021_renouvelerlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
