# Generated by Django 5.1.6 on 2025-08-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0022_alter_bien_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='louer',
            name='type_bien',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendre',
            name='type_bien',
            field=models.CharField(max_length=255),
        ),
    ]
