# Generated by Django 5.1.6 on 2025-08-20 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0023_alter_louer_type_bien_alter_vendre_type_bien'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsTransactionVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recu_vente', models.FileField(upload_to='documents_vente/recus/', verbose_name='Reçu de vente')),
                ('copie_attestation_mandataire', models.FileField(upload_to='documents_vente/attestations/', verbose_name="Copie d'attestation du mandataire")),
                ('copie_attestations_heritage', models.FileField(upload_to='documents_vente/heritage/', verbose_name="Copie(s) d'attestation(s) de passation d'héritage")),
                ('nouveau_titre_foncier', models.FileField(blank=True, null=True, upload_to='documents_vente/titres_fonciers/', verbose_name='Nouveau titre foncier (Optionnel)')),
                ('temoin1_proprietaire_cni_recto', models.ImageField(upload_to='documents_vente/temoins/cni_proprietaire/', verbose_name='CNI Recto du témoin (Propriétaire)')),
                ('temoin1_proprietaire_cni_verso', models.ImageField(upload_to='documents_vente/temoins/cni_proprietaire/', verbose_name='CNI Verso du témoin (Propriétaire)')),
                ('nom_temoin1_proprietaire', models.CharField(max_length=255, verbose_name='Nom et prénom du témoin (Propriétaire)')),
                ('temoin1_client_cni_recto', models.ImageField(upload_to='documents_vente/temoins/cni_client/', verbose_name='CNI Recto du témoin (Client)')),
                ('temoin1_client_cni_verso', models.ImageField(upload_to='documents_vente/temoins/cni_client/', verbose_name='CNI Verso du témoin (Client)')),
                ('nom_temoin1_client', models.CharField(max_length=255, verbose_name='Nom et prénom du témoin (Client)')),
                ('temoin2_proprietaire_cni_recto', models.ImageField(upload_to='documents_vente/temoins/cni_proprietaire/', verbose_name='CNI Recto du deuxième témoin (Propriétaire)')),
                ('temoin2_proprietaire_cni_verso', models.ImageField(upload_to='documents_vente/temoins/cni_proprietaire/', verbose_name='CNI Verso du deuxième témoin (Propriétaire)')),
                ('nom_temoin2_proprietaire', models.CharField(max_length=255, verbose_name='Nom et prénom du deuxième témoin (Propriétaire)')),
                ('temoin2_client_cni_recto', models.ImageField(upload_to='documents_vente/temoins/cni_client/', verbose_name='CNI Recto du deuxième témoin (Client)')),
                ('temoin2_client_cni_verso', models.ImageField(upload_to='documents_vente/temoins/cni_client/', verbose_name='CNI Verso du deuxième témoin (Client)')),
                ('nom_temoin2_client', models.CharField(max_length=255, verbose_name='Nom et prénom du deuxième témoin (Client)')),
                ('temoin3_proprietaire_cni_recto', models.ImageField(upload_to='documents_vente/temoins/cni_proprietaire/', verbose_name='CNI Recto du troisième témoin (Propriétaire)')),
                ('temoin3_proprietaire_cni_verso', models.ImageField(upload_to='documents_vente/temoins/cni_proprietaire/', verbose_name='CNI Verso du troisième témoin (Propriétaire)')),
                ('nom_temoin3_proprietaire', models.CharField(max_length=255, verbose_name='Nom et prénom du troisième témoin (Propriétaire)')),
                ('temoin3_client_cni_recto', models.ImageField(upload_to='documents_vente/temoins/cni_client/', verbose_name='CNI Recto du troisième témoin (Client)')),
                ('temoin3_client_cni_verso', models.ImageField(upload_to='documents_vente/temoins/cni_client/', verbose_name='CNI Verso du troisième témoin (Client)')),
                ('nom_temoin3_client', models.CharField(max_length=255, verbose_name='Nom et prénom du troisième témoin (Client)')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('valide_par_admin', models.BooleanField(default=False)),
                ('bien_vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_vente', to='IMMOBILIER_APP.vendre')),
                ('demande_bien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents_vente', to='IMMOBILIER_APP.demandebien')),
            ],
        ),
    ]
