# Generated by Django 5.1.6 on 2025-08-20 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0024_documentstransactionvente'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstransactionvente',
            name='date_validation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='documentstransactionvente',
            name='proprietaire',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents_vente_proprietaire', to='IMMOBILIER_APP.utilisateur'),
        ),
    ]
