# Generated by Django 5.1.6 on 2025-08-28 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0026_adminlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='louer',
            name='image_principale',
        ),
        migrations.RemoveField(
            model_name='vendre',
            name='image_principale',
        ),
        migrations.CreateModel(
            name='ImageBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='biens_images/')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='IMMOBILIER_APP.bien')),
                ('bien_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='IMMOBILIER_APP.louer')),
                ('bien_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='IMMOBILIER_APP.vendre')),
            ],
        ),
    ]
