# Generated by Django 5.1.6 on 2025-08-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0027_remove_louer_image_principale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='image',
        ),
    ]
