# Generated by Django 5.1.6 on 2025-08-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMMOBILIER_APP', '0028_remove_bien_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='louer',
            name='message_de_refus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='louer',
            name='nombre_de_refus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendre',
            name='message_de_refus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendre',
            name='nombre_de_refus',
            field=models.IntegerField(default=0),
        ),
    ]
